# Mnemosyne Configuration
# Create a file named config.yaml in the same directory as this file.

# Server configuration
server:
  host: localhost
  port: 8080

# Database configuration
database:
  host: localhost
  port: 5432
  user: mnemosyne
  password: mnemosyne
  dbname: mnemosyne
  sslmode: disable

# Git repository configuration
git:
  # Repository settings
  # For SSH (recommended for private repos):
  # url: git@github.com:username/repository.git
  # For HTTPS (public repos):
  url: https://github.com/octocat/Hello-World.git
  
  branch: main
  local_path: data/vault_clone
  
  # Authentication
  # For SSH authentication (leave blank to use default SSH keys):
  # ssh_key_path: ~/.ssh/id_rsa  # Or ~/.ssh/id_ed25519
  
  # Sync settings
  auto_sync: true
  sync_interval: 5m # Valid time units: s, m, h
  
  # Performance settings
  shallow_clone: true # Faster clone, no history needed for visualization
  single_branch: true # Only clone the specified branch

# Graph processing configuration
graph:
  # Layout algorithm settings
  layout:
    algorithm: force-directed  # Options: force-directed, hierarchical
    iterations: 500           # Number of iterations for force-directed layout
    initial_temp: 1000.0      # Initial temperature for simulated annealing
    cooling_rate: 0.95        # Temperature cooling rate
    optimal_distance: 100.0   # Optimal distance between connected nodes
  
  # Cache settings
  cache:
    enabled: true
    ttl: 30m                  # Cache time-to-live
    max_memory_size: 104857600 # Max memory for cache in bytes (100MB)
  
  # Processing settings
  batch_size: 100             # Number of files to process at once
  max_concurrency: 4          # Max concurrent goroutines for processing